### ISSUE TITLE
Typo in shutdown endpoint enabling

### ISSUE THREAD

**Issue by charm911** [ErnestOrt/Trampoline#69] opened 2018-07-26 01:57 UTC
In the ScriptContentsProvider class, there is a typo to the "-D" shutdown endpoint.

It should be endpoint.shutdown.enabled ... not "endpointS".  

This prevents the shutdown from happening if the provided microservice does not itself enable it (as it is disabled by default).

ref: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-enabling-endpoints

**Comment by ErnestOrt** [comment] 2018-07-30 13:30
Good point!

We will fix it as soon as possible.

Thanks for your feedback!

Cheers!

**Comment by ErnestOrt** [comment] 2018-07-31 16:25
@charm911 

Just to clarify

``endpoints.shutdown.enabled=true``

This is a deprected endpoint included just to avoid old version issues.

http://www.baeldung.com/spring-boot-shutdown

This is the current one:

``management.endpoint.shutdown.enabled=true``


https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

Closing since it's not a bug.

Have a nice week!

**Closed by ErnestOrt** 2018-07-31 16:25 UTC
Labels: bug
